# Generated by Django 4.1.4 on 2022-12-25 16:45
import phonenumbers
from django.db import migrations


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.filter(owner_pure_phone=''):
        normalized_phone_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
        flat.owner_pure_phone = normalized_phone_number
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owner_pure_phone_alter_flat_has_balcony_and_more'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers)
    ]
