# Generated by Django 4.1.4 on 2022-12-25 17:42
import phonenumbers
from django.db import migrations


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    flat_set = Flat.objects.all()
    for flat in flat_set.iterator():
        normalized_phone_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
        if phonenumbers.is_valid_number(normalized_phone_number):
            flat.owner_pure_phone = normalized_phone_number
            flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_alter_flat_owner_pure_phone'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers)
    ]
