# Generated by Django 4.1.4 on 2022-12-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_complaint_client_alter_complaint_flat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owned_flats',
            new_name='flats',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
