# Generated by Django 4.1.4 on 2022-12-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_rename_owned_flats_owner_flats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='owners', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
    ]
